			<h3>About Us </h3>
				<div class="abt_img_div"><img src="img/logo2.png" alt="Star Security Bouncers, Pune" title="Star Security Bouncers, Pune" /></div>
				<p>
					We at <strong>Star Security animated Bouncer</strong> are a team who provide <strong>Premium Security with Bouncer Class</strong> First point security personnel. We provide security for multiple category of services which are provided in our website. Our customers reputation and your security is our first priority. With STAR feel secure....
				</p>
				<p>
					We provide Special Category Security Management, Our Strategic Risk Management team conducts a formal inspection, risk prior to deciding on the number of positions and personnel required.  We also provide a formal NDA signed from STAR SECUIRTY BOUNCERS to ensure that organizational information and data shared with us is secure.   Post our Risk Assessment we also provide our inputs in respect to residual risks, requirement of positions, non-requirement of positions for a secure economic viability of the <em><strong style="color: #F44336;"> BOUNCER CLASS PREMIUM SERVICE......</strong></em>  <strong><a href="about_us.php">Read More</a></strong>
				</p>