	<header>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                    <a class="navbar-brand" href="index.php">
	                    <img src="img/logo.png" alt="logo" class="logo_img">
	                    <p class="logo_name">Star Security & Bouncer</p> 
	                    <hr class="hr" />
	                    <h5 style="color:#FFF59D;margin-left:80px;"><i class="tag_line">..... feel Secured .....</i></h5></a>
               	
                </div>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="index.php">Home</a></li>
                        <li><a href="about-us.php">About Us</a></li>
                        <li><a href="team.php">Team</a></li>
                        <li><a href="training_development.php">Training Development</a></li>
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle " data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">Services <b class=" icon-angle-down"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="campus-perimeter-combat-security.php">Campus Perimeter Combat Security</a></li>
                                <li><a href="women-safety-and-transport-security.php">Women Safety and Transport Security</a></li>
                                <li><a href="vvip-security.php">VVIP Security</a></li>
                                <li><a href="event-management-security.php">Event Management Security</a></li>
                                <li><a href="banking-institutional-and-customer-safety.php">Banking Institutional and Customer Safety</a></li>
                                <li><a href="secure-transit-security.php">Secure Transit Security</a></li>
                               <!--  <li><a href="customized_personal_protection_and_investigation.php">Customized Personal Protection & Investigation</a></li> -->
                                <li><a href="real-estate-and-market-place-security.php">Real Estate and Market Place Security</a></li>
                            </ul>
                        </li>
                        
                        <li><a href="clients.php">Clients</a></li>
                        <li ><a href="our-locations.php">Service Locations</a></li>
                        <li><a href="contact.php">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
	</header>
	<?php include 'floating-bar.php' ?>