			<div class="col-lg-4" style="border-left: 1px solid rgba(158, 158, 158, 0.17);">
				<!-- <img src="img/dummies/d.jpg" alt="" class="align-left" /> -->
				<h4>Our Services </h4>
					<ul class="services_ul">
					<li><i class="fa fa-check-circle"></i> <a href="campus-perimeter-combat-security.php">Campus Perimeter Combat Security</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Corporate Security Services</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Security for Mall / Commercial Complexes</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Security for Celebrities</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Residential Society / Complexes Security</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Security for Personal Guard</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Security for Warehouses / Godown </a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Security for Banks / ATMs</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Security Services for Hospital</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Security Services for Educational Institutions</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Security Guards for Hotels / Restaurants</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="">Bouncer Security Services</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="women-safety-and-transport-security.php">Women Safety and Transport Security</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="vvip-security.php">VVIP Security</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="event-management-security.php">Event Management Security</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="banking-institutional-and-customer-safety.php">Banking Institutional and Customer Safety</a></li>
					<li><i class="fa fa-check-circle"></i> <a href="secure-transit-security.php">Secure Transit Security</a></li>
					<!-- <li><i class="fa fa-check-circle"></i> <a href="customized_personal_protection_and_investigation.php">Customized Personal Protection & Investigation</a></li> -->
					<li><i class="fa fa-check-circle"></i> <a href="real-estate-and-market-place-security.php">Real Estate and Market Place Security</a></li>
				</ul>				
			</div>