              <div class="row">
                  <div class="col-lg-12">
                     <h4 class="heading h4">Our Services</h4>
                     <div class="row">
                        <div class="col-lg-3">
                           <div class="box">
                              <div class="box-gray aligncenter">
                                 <h5>Campus Perimeter Combat Security</h5>
                                 <div class="icon">
                                    <!-- <i class="fa fa-desktop fa-3x"></i> -->
                                    <img src="img/services/campussecurity.jpg" alt="Campus Perimeter Combat Security Bouncers" title="Campus Perimeter Combat Security Bouncers" />
                                 </div>
                                 <p>
                                    We provide our standards of operations as an insight to enable organizations approve of our standard operating procedures.
                                 </p>
                              </div>
                              <div class="box-bottom">
                                 <a href="campus-perimeter-combat-security.php">Read more</a>
                              </div>
                           </div>
                        </div>
                        <div class="col-lg-3">
                           <div class="box">
                              <div class="box-gray aligncenter">
                                 <h5>Women Safety and Transport Security</h5>
                                 <div class="icon">
                                    <!-- <i class="fa fa-desktop fa-3x"></i> -->
                                    <img src="img/services/women_safety.jpg" alt="Women Safety and Transport Security Bouncers" title="Women Safety and Transport Security Bouncers" />
                                 </div>
                                 <p style="text-align:justify;">
                                    This service is provided for the IT and ITES industry to ensure compliance to the regulatory requirements.
                                 </p>
                              </div>
                              <div class="box-bottom">
                                 <a href="women-safety-and-transport-security.php">Read more</a>
                              </div>
                           </div>
                        </div>
                        <div class="col-lg-3">
                           <div class="box">
                              <div class="box-gray aligncenter">
                                 <h5>VVIP Security</h5>
                                 <div class="icon">
                                    <!-- <i class="fa fa-desktop fa-3x"></i> -->
                                    <img src="img/services/vvipsecurity.jpg" alt="VVIP Security Bouncers" title="VVIP Security Bouncers" />
                                 </div>
                                 <p>
                                    Business houses, Celebrities, Manufacturing units, Event management companies and their clients, Hotel Industry, Banking
                                 </p>
                              </div>
                              <div class="box-bottom">
                                 <a href="vvip-security.php">Read more</a>
                              </div>
                           </div>
                        </div>
                        <div class="col-lg-3">
                           <div class="box">
                              <div class="box-gray aligncenter">
                                 <h5>Event Management <br/> Security </h5>
                                 <div class="icon">
                                    <!-- <i class="fa fa-desktop fa-3x"></i> -->
                                    <img src="img/services/eventsecurity.jpg" alt="Event Management Security Bouncers" />
                                 </div>
                                 <p>
                                    Security risk assessment covering event location, Entry Admission Pass verification
                                    , Security checks, Management of Parking order
                                 </p>
                              </div>
                              <div class="box-bottom">
                                 <a href="event-management-security.php">Read more</a>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-lg-12">
                     <div class="row">
                        <div class="col-lg-3">
                           <div class="box">
                              <div class="box-gray aligncenter">
                                 <h5>Banking  Institutional and Customer Safety </h5>
                                 <div class="icon">
                                    <img src="img/services/banksecurity.jpg" alt="Banking  Institutional and Customer Safety" title="Banking  Institutional and Customer Safety" />
                                 </div>
                                 <p>
                                    Aligning to the risk assessed by respective banks for financial and customer transactions,   travel security as per requirements.
                                 </p>
                              </div>
                              <div class="box-bottom">
                                 <a href="banking-institutional-and-customer-safety.php">Read more</a>
                              </div>
                           </div>
                        </div>
                        <div class="col-lg-3">
                           <div class="box">
                              <div class="box-gray aligncenter">
                                 <h5>Secure Transit <br/> Security</h5>
                                 <div class="icon">
                                    <!-- <i class="fa fa-desktop fa-3x"></i> -->
                                    <img src="img/services/securetransit.jpg" alt="Secure Transit Security Bouncers" title="Secure Transit Security Bouncers" />
                                 </div>
                                 <p>
                                    Enabling organizations apply and seek necessary government permissions, 
                                    Planning the transit route maps
                                 </p>
                              </div>
                              <div class="box-bottom">
                                 <a href="secure-transit-security.php">Read more</a>
                              </div>
                           </div>
                        </div>
                        <div class="col-lg-3">
                           <div class="box">
                              <div class="box-gray aligncenter">
                                 <h5>Real Estate and Market Place Security </h5>
                                 <div class="icon">
                                    <!-- <i class="fa fa-desktop fa-3x"></i> -->
                                    <img src="img/services/real_estate.jpg" alt="Real Estate and Market Place Security Bouncers" title="Real Estate and Market Place Security Bouncers" />
                                 </div>
                                 <p>
                                    High Security requirement zones, Banks and customer service centers, Multi-tenant commercial premises
                                 </p>
                              </div>
                              <div class="box-bottom">
                                 <a href="real-estate-and-market-place-security.php">Read more</a>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>