 <h3>Why Us</h3>
               <ul>
                  <li>
                     <p>A Team of over 300+ well build Bouncer Class security personnels.</p>
                  </li>
                  <li>
                     <p>We are rated in Top in our industry. </p>
                  </li>
                  <li>
                     <p>Experience in Managing Multiple Assignments for more than 10 years.</p>
                  </li>
                  <li>
                     <p>We Continue to Obtain the required Authorization & certification from Dept of Police.</p>
                  </li>
                  <li>
                     <p>Liaison with Government Law and order keeping Agencies</p>
                  </li>
                  <li>
                     <p>We Manage Prevent and Protect People, Premise, Personalities, Property </p>
                  </li>
               </ul>